---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jnmaih
spec:
  profile:
    displayName: Juergen Maihoefner
    email: juergen@example.com
  memberOf: [backstage, boxoffice, team-b]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-nginx-cncf-nbg
  namespace: default
  annotations:
    backstage.io/kubernetes-cluster: local
    backstage.io/kubernetes-namespace: backstage-demo
    backstage.io/kubernetes-label-selector: app=demo-nginx
    backstage.io/kubernetes-id: demo-nginx
    backstage.io/techdocs-ref: "dir: demo-nginx"
    endoflife.date/products: nginx@1.25

spec:
  type: service
  lifecycle: experimental
  owner: team-b
